version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: products-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: productsdb
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: spring-docker-app
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/productsdb
    ports:
      - "8080:8080"

volumes:
  mongo-data:
